---
# Traefik
traefik_user: traefik-user
traefik_storage_directory: "/home/{{ traefik_user }}/traefik-storage"
traefik_config_location: "{{ traefik_storage_directory }}/config"
traefik_config_dynamic_location: "{{ traefik_storage_directory }}/config_dynamic"
traefik_certs_location: "{{ traefik_storage_directory }}/certs"
traefik_image: docker.io/traefik
traefik_tag: v3.5.0
traefik_web_port: 10080
traefik_websecure_port: 10443
traefik_dashboard_port: 8080

# Immich
immich_user: immich-user
immich_storage_directory: "/home/{{ immich_user }}/immich-storage"
immich_upload_location: "{{ immich_storage_directory }}/library"
immich_db_data_location: "{{ immich_storage_directory }}/postgres"
immich_network: immich_network
immich_server_image: ghcr.io/immich-app/immich-server
immich_server_tag: v1.135.3
immich_server_port: 20000
immich_machine_learning_image: ghcr.io/immich-app/immich-machine-learning
immich_machine_learning_tag: v1.135.3
immich_redis_image: docker.io/valkey/valkey
immich_redis_tag: 8-bookworm@sha256:fec42f399876eb6faf9e008570597741c87ff7662a54185593e74b09ce83d177
immich_postgres_image: ghcr.io/immich-app/postgres
immich_postgres_tag: 14-vectorchord0.4.3-pgvectors0.2.0
immich_db_database_name: immich_database
immich_db_username: immich_pg_user

# Nextcloud
nextcloud_user: nextcloud-user
nextcloud_storage_directory: "/home/{{ nextcloud_user }}/nextcloud-storage"
nextcloud_apache_config_location: "{{ nextcloud_storage_directory }}/apache-config"
nextcloud_config_location: "{{ nextcloud_storage_directory }}/config"
nextcloud_data_location: "{{ nextcloud_storage_directory }}/data"
nextcloud_db_data_location: "{{ nextcloud_storage_directory }}/postgres"
nextcloud_network: nextcloud_network
nextcloud_server_image: docker.io/nextcloud
nextcloud_server_tag: 31.0.7-apache
nextcloud_server_port: 20100
nextcloud_redis_image: docker.io/redis
nextcloud_redis_tag: 8.0.3
nextcloud_postgres_image: docker.io/postgres
nextcloud_postgres_tag: 16.9
nextcloud_db_database_name: nextcloud_database
nextcloud_db_username: nextcloud_pg_user

# PhotoPrism
photoprism_user: photoprism-user
photoprism_storage_directory: "/home/{{ photoprism_user }}/photoprism-storage"
photoprism_originals_location: "{{ photoprism_storage_directory }}/originals"
photoprism_storage_location: "{{ photoprism_storage_directory }}/storage"
photoprism_db_data_location: "{{ photoprism_storage_directory }}/mariadb"
photoprism_network: photoprism_network
photoprism_server_image: docker.io/photoprism/photoprism
photoprism_server_tag: 250707
photoprism_server_port: 20200
photoprism_mariadb_image: docker.io/mariadb
photoprism_mariadb_tag: 11.8.2
photoprism_db_database_name: photoprism_database
photoprism_db_username: photoprism_mariadb_user

