[tools]
"core:python" = "3.14.5"
"core:ruby" = "3.4.9"
"github:jqlang/jq" = "jq-1.8.1"
"github:mikefarah/yq" = {
    version = "v4.53.2",
    rename_exe = "yq",
}
"github:sigstore/cosign" = "v3.0.6"
"github:k3d-io/k3d" = "v5.8.3"
"github:astral-sh/uv" = "0.11.18"
"github:tilt-dev/tilt" = "v0.37.3"
"github:kubernetes-sigs/kustomize" = "kustomize/v5.8.1"
"github:getsops/sops" = {
    version = "v3.13.1",
    bin = "sops",
}
"github:FiloSottile/age" = "v1.3.1"
"aqua:kubernetes/kubernetes/kubectl" = "v1.36.1"
"aqua:helm/helm" = "v4.2.1"

[settings]
locked = true
lockfile = true
experimental = true # mise postinstall hook is experimental for now
always_keep_download = true # mise removes the tarballs after install by default, but they are needed for attestation verification
github.slsa = true # explicitly enable slsa for github endpoints
github.github_attestations = true # explicitly enable attestation checking for github endpoints

[env]
MISE_DOWNLOADS_DIR = "{{ env.MISE_DATA_DIR }}/downloads"
MISE_TASK_OUTPUTS = "{{ config_root }}/../../.direnv/mise-task-outputs"
BUNDLE_PATH = "{{ config_root }}/../../.direnv/ruby/bundle"
BUNDLE_GEMFILE = "{{ config_root }}/../../dependencies/ruby/Gemfile"
BUNDLE_BIN = "{{ config_root }}/../../.direnv/ruby/bin"
VAGRANT_HOME = "{{ config_root }}/../../.direnv/vagrant.d"
ANSIBLE_ROLES_PATH = "{{ config_root }}/../../.direnv/ansible-galaxy/roles"
ANSIBLE_COLLECTIONS_PATH = "{{ config_root }}/../../.direnv/ansible-galaxy/collections"
KUBECONFIG = "{{ config_root }}/../../.direnv/kubeconfig"
HELM_PLUGINS = "{{ config_root }}/../../.direnv/helm/plugin"
HELM_CACHE_HOME="{{ config_root }}/../../.direnv/helm/cache"
HELM_CONFIG_HOME="{{ config_root }}/../../.direnv/helm/config"
HELM_CONTENT_CACHE="{{ env.HELM_CACHE_HOME }}/content"
HELM_DATA_HOME="{{ config_root }}/../../.direnv/helm/data"
HELM_REGISTRY_CONFIG="{{ env.HELM_CONFIG_HOME }}/registry/config.json"
HELM_REPOSITORY_CACHE="{{ env.HELM_CACHE_HOME }}/repository"
HELM_REPOSITORY_CONFIG="{{ env.HELM_CONFIG_HOME }}/repositories.yaml"
_.path = [ "{{ env.BUNDLE_BIN }}" ]
_.python.venv = { path = "{{ config_root }}/../../.direnv/venv", create = true }

[tasks.verify-python]
description = "Manually verify python attestation"
run = """
    set -euo pipefail

    {{ config_root }}/../../scripts/mise-verify-github-attestation.sh \
        "${MISE_DOWNLOADS_DIR}/python/$(mise current core:python)" \
        "astral-sh/python-build-standalone"
    touch "${MISE_TASK_OUTPUTS}/python-verified"
"""
sources = ["{{ exec(command='mise where core:python') }}"]
outputs = ["{{ env.MISE_TASK_OUTPUTS }}/python-verified"]

[tasks.verify-ruby]
description = "Manually verify ruby attestation"
run = """
    set -euo pipefail

    {{ config_root }}/../../scripts/mise-verify-github-attestation.sh \
        "${MISE_DOWNLOADS_DIR}/ruby/$(mise current core:ruby)" \
        "jdx/ruby"
    touch "${MISE_TASK_OUTPUTS}/ruby-verified"
"""
sources = ["{{ exec(command='mise where core:ruby') }}"]
outputs = ["{{ env.MISE_TASK_OUTPUTS }}/ruby-verified"]

[tasks.verify-kubectl]
description = "Manually verify kubectl signature"
run = """
    set -euo pipefail

    version="$(mise current aqua:kubernetes/kubernetes/kubectl)"
    base="https://dl.k8s.io/${version}/bin/linux/amd64"
    {{ config_root }}/../../scripts/mise-verify-cosign.sh \
        "$(mise where aqua:kubernetes/kubernetes/kubectl)/kubectl" \
        "${base}/kubectl.sig" \
        "${base}/kubectl.cert" \
        "krel-staging@k8s-releng-prod.iam.gserviceaccount.com" \
        "https://accounts.google.com"
    touch "${MISE_TASK_OUTPUTS}/kubectl-verified"
"""
sources = ["{{ exec(command='mise where aqua:kubernetes/kubernetes/kubectl') }}"]
outputs = ["{{ env.MISE_TASK_OUTPUTS }}/kubectl-verified"]

[tasks.verify-helm]
description = "Manually verify helm signature"
run = """
    set -euo pipefail

    version="$(mise current aqua:helm/helm)"
    hash_file_url="https://get.helm.sh/helm-${version}-linux-amd64.tar.gz.sha256"
    gpg_key_url="https://keybase.io/r6by/pgp_keys.asc"
    tarball_dir="${MISE_DOWNLOADS_DIR}/aqua-helm-helm/$(mise current aqua:helm/helm)"
    signature_url_base="https://github.com/helm/helm/releases/download/${version}"
    {{ config_root }}/../../scripts/mise-verify-hash.sh \
        "sha256sum" \
        "${tarball_dir}" \
        "${hash_file_url}"
    {{ config_root }}/../../scripts/mise-verify-gpg.sh \
        "${tarball_dir}" \
        "${gpg_key_url}" \
        "${signature_url_base}"
    touch "${MISE_TASK_OUTPUTS}/helm-verified"
"""
sources = ["{{ exec(command='mise where aqua:helm/helm') }}"]
outputs = ["{{ env.MISE_TASK_OUTPUTS }}/helm-verified"]

[tasks.python-dep-install]
description = "Install python dependencies"
depends = ["verify-python"]
run = """
    set -euo pipefail

    uv pip install -r {{ config_root }}/../../dependencies/python/pylock.toml
    touch "${MISE_TASK_OUTPUTS}/python-dep-installed"
"""
sources = ["{{ config_root }}/../../dependencies/python/pylock.toml"]
outputs = ["{{ env.MISE_TASK_OUTPUTS }}/python-dep-installed"]

[tasks.ruby-dep-install]
description = "Install ruby dependencies"
depends = ["verify-ruby"]
run = """
    set -euo pipefail

    export BUNDLE_DEPLOYMENT "true" # this disables the auto generation/updating of the lockfile when installing, which would defeat its purpose
    bundle install --gemfile {{ config_root }}/../../dependencies/ruby/Gemfile
    touch "${MISE_TASK_OUTPUTS}/ruby-dep-installed"
"""
sources = ["{{ config_root }}/../../dependencies/ruby/Gemfile.lock"]
outputs = ["{{ env.MISE_TASK_OUTPUTS }}/ruby-dep-installed"]

[tasks.ansible-galaxy-dep-install]
description = "Install ansible-galaxy dependencies"
depends = ["python-dep-install"]
run = """
    set -euo pipefail

    ansible-galaxy install -r {{ config_root }}/../../dependencies/ansible/requirements.yaml
    ansible-galaxy collection install -r {{ config_root }}/../../dependencies/ansible/requirements.yaml
    touch "${MISE_TASK_OUTPUTS}/ansible-galaxy-dep-installed"
"""
sources = ["{{ config_root }}/../../dependencies/ansible/requirements.yml"]
outputs = ["{{ env.MISE_TASK_OUTPUTS }}/ansible-galaxy-dep-installed"]

[tasks.helm-plugin-symlink]
description = "Symlink installed helm plugins to the helm plugins directory"
depends = ["verify-helm"]
run = """
    set -euo pipefail

    mkdir -p "$HELM_PLUGINS"
    # Preform symlinking of plugins
    # ln -sfn "$(mise where github:databus23/helm-diff)" "$HELM_PLUGINS/helm-diff"
    touch "${MISE_TASK_OUTPUTS}/helm-plugin-symlinked"
"""
sources = ["{{ config_root }}/mise.toml"] # Plugins are installed via mise but need to be symlinked for helm to find them.
outputs = ["{{ env.MISE_TASK_OUTPUTS }}/helm-plugin-symlinked"]

[tasks.bootstrap]
description = "Full bootstrap"
depends = [
    "verify-python",
    "verify-ruby",
    "verify-kubectl",
    "verify-helm",
    "python-dep-install",
    "ruby-dep-install",
    "ansible-galaxy-dep-install",
    "helm-plugin-symlink",
]

[hooks]
postinstall = """
    set -euo pipefail

    mkdir -p "$MISE_TASK_OUTPUTS"
    mise run bootstrap
"""

