---
apiVersion: v1
kind: Service
metadata:
  # The default immich server configuration expects the ml container to be available at
  # http://immich-machine-learning:3003. As such, a deviation from the default service
  # name is neccessary to avoid explicitly configuring it in the admin ui.
  name: immich-machine-learning
  namespace: immich
spec:
  selector:
    app: machine-learning
  ports:
    - port: 3003
      targetPort: 3003

