---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
        connectsToRedis: "true"
        connectsToDatabase: "true"
        connectsToMachineLearning: "true"
    spec:
      containers:
        - name: server
          image: ghcr.io/immich-app/immich-server:v2.4.1
          env:
            - name: DB_HOSTNAME
              value: database
            - name: DB_PORT
              value: "5432"
            - name: REDIS_HOSTNAME
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: DB_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: dbDatabaseName
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: dbUsername
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: dbPassword
          ports:
            - containerPort: 2283
          volumeMounts:
            - name: upload
              mountPath: /usr/src/app/upload
      volumes:
        - name: upload
          persistentVolumeClaim:
            claimName: upload

