apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: digitalocean-dns-credentials
    namespace: cert-manager
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: digitalocean-dns-credentials
          stringData:
            api-token: ENC[AES256_GCM,data:e+JabhbHW2egVQRJnfPj6jfTAYNkaufE/f1BKQZISErPq3dDOIs4dOt4OF44sJlXLSQkvp3kyJNzYYEwQKaB2RQmn/95Yh4=,iv:iYuk77FPb1dfakn3VN5qqMxEyeCPzLcyZzoiyN0j264=,tag:hoydvq61uHqRmzAvUZjl4A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZkJGMnZpM2RKeDJYdzJU
            SGlZNlhGN3F2Q1I2NERqREI5RmIrQTg1WndZCmM2Y21QczYyL1NoQnVvSjg2bzFJ
            ck1yNlJieS8wN09DcVlvVXUvTmxUREUKLS0tIHkyTFpwcllIMnFYZFUwUmRxcTdS
            cW9kRXc3eFVPY3k0L2FuMlJpaUlLZVkKXgTANFhIeS1GO/2psjbcqniKSCZ7Ce+U
            fD5CDVciVR/4FKrlEKX2moP68DItqtDZTiaoAAD2/MewlevTD1fENg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cek8pae0a8mvptlwcfnhahkaqlyu7u8stg48uncexvf24trg9pgqs5pehk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T22:13:51Z"
    mac: ENC[AES256_GCM,data:ndtPMBSGinBTh0cyCeN1ErLTdXV/kXFNC9Vg4FMzLLIJnYs1mA2Jmht0QSQ8TuL5P4im6/e+xGBkNJ/NBvykngq4X7pUcm0z5C840nObc7fhFYKNU9rXN+n49KarrotvSC9MNSODb2Mzs4Yb2BiHoTlZYU2HN0dB724avEFUDY8=,iv:pvg6PPEfHvMkpYPsiBMjRCnOyRVnNQATWEC08tnk8JE=,tag:xhWDmov6lydGItF9F5u1dQ==,type:str]
    version: 3.13.1
