---
- name: Ensure DNS port forward rules are present in ufw manual configuration
  ansible.builtin.blockinfile:
    path: /etc/ufw/before.rules
    marker: "# {mark} ANSIBLE NAT RULES FOR DNS"
    block: |
      -A PREROUTING -i eth0 -p tcp --dport 53 -j REDIRECT --to-ports {{ pihole.container.server.config.dns.port }}
      -A PREROUTING -i eth0 -p udp --dport 53 -j REDIRECT --to-ports {{ pihole.container.server.config.dns.port }}
      -A PREROUTING -i tailscale0 -p tcp --dport 53 -j REDIRECT --to-ports {{ pihole.container.server.config.dns.port }}
      -A PREROUTING -i tailscale0 -p udp --dport 53 -j REDIRECT --to-ports {{ pihole.container.server.config.dns.port }}
      -A OUTPUT -o lo -p tcp --dport 53 -j REDIRECT --to-ports {{ pihole.container.server.config.dns.port }}
      -A OUTPUT -o lo -p udp --dport 53 -j REDIRECT --to-ports {{ pihole.container.server.config.dns.port }}
    insertafter: "# NAT_RULE_MARKER"
    create: false

- name: Ensure DNS traffic is allowed
  community.general.ufw:
    rule: allow
    port: "{{ pihole.container.server.config.dns.port }}"
    proto: "{{ item }}"
  loop:
    - tcp
    - udp

- name: Ensure ufw rules are reloaded after updating dns specific rules
  community.general.ufw:
    state: reloaded
  async: 3
  poll: 0

