---
- name: Bootstrap python
  hosts: charon
  gather_facts: false
  roles:
    - python

- name: Configure charon node
  hosts: charon
  roles:
    - sshd
    - mirror
    - base/charon
    - base
    - tailscale
    - zfs
    - wakeonlan
    - firewall
    - traefik
    - service/immich
    - service/filebrowser
    - service/photoprism
    - service/gitea
    - service/syncthing

