---
- name: Run staging environment for test
  ansible.builtin.import_playbook: docker-staging.yaml
  vars:
    env: test
    immich_port: 30080
    ssh_port: 30022

- name: Remove test containers after test execution
  hosts: localhost
  vars:
    deployserver_container_name: deployserver_test

  tasks:
    - name: Ensure container is stopped
      community.docker.docker_container:
        name: "{{ deployserver_container_name }}"
        state: absent

