---
- name: Create necessary certificates on local environment to reuse during deployment of containers
  hosts: configserver
  roles:
    - certificates

- name: Configure server node
  hosts: deployserver
  roles:
    - base
    # - firewall TODO
    - user
    - role: immich
      become: true
      become_user: "{{ podman_user }}"
    - alpine

