---
- name: Create necessary certificates on local environment to reuse during deployment of containers
  hosts: configserver
  roles:
    - certificates

- name: Configure server node
  hosts: deployserver
  roles:
    - base
    # - firewall TODO
    - user
    - role: immich
      become: yes
      become_method: su
      become_flags: "-l"
      become_user: "{{ podman_user }}"
  environment:
    CONTAINER_HOST: "{{ 'unix:///run/podman/podman.sock' if ansible_connection == 'docker' else '' }}"

