---
- name: Enable firewall to forward dev port
  hosts: localhost
  tasks:
    - name: Enable http service on public interface
      ansible.posix.firewalld:
        service: http
        zone: public
        state: enabled

    - name: Enable dev port on public interface
      ansible.posix.firewalld:
        port: "{{ item }}/tcp"
        zone: public
        state: enabled
      loop:
        - "{{ immich_server_port }}"
        - "{{ nextcloud_server_port }}"

