---
- name: "Ensure {{ podman_user }} is created and locked to prevent logins on the user"
  ansible.builtin.user:
    name: "{{ podman_user }}"
    create_home: true
    home: "{{ podman_user_home }}"
    password: "{{ podman_user_password }}"
    shell: /bin/sh
    state: present

- name: Ensure podman tmp file storage environment variable is exported in .ashrc
  ansible.builtin.lineinfile:
    path: "{{ podman_user_home }}/.ashrc"
    regexp: '^export XDG_RUNTIME_DIR'
    line: 'export XDG_RUNTIME_DIR=/run/user/"$(id -u)"'
    state: present
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
    create: true
    insertafter: EOF

- name: Ensure user's ansible tmp directory exists
  ansible.builtin.file:
    path: "{{ podman_user_home }}/.ansible/tmp"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
    mode: 0700

- name: Ensure user's bin directory exists
  ansible.builtin.file:
    path: "{{ podman_user_home }}/bin"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
    mode: 0755

- name: Create start-container.sh with XDG_RUNTIME_DIR export
  ansible.builtin.copy:
    dest: "{{ podman_user_home }}/bin/container-executor.sh"
    content: |
      #!/bin/sh
      export XDG_RUNTIME_DIR=/run/user/$(id -u)
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
    mode: 0755

- name: Create OpenRC init script to restart podman user containers, in case the system reboots
  ansible.builtin.copy:
    dest: "/etc/init.d/{{ podman_user }}-container-executor"
    content: |
      #!/sbin/openrc-run

      description="Start user podman container"

      start() {
          ebegin "Starting podman containers for user {{ podman_user }}"
          su - {{ podman_user }} -c '/home/{{ podman_user }}/bin/container-executor.sh'
          eend $?
      }
    owner: root
    group: root
    mode: 0755

- name: Add OpenRC service to default runlevel
  ansible.builtin.service:
    name: "{{ podman_user }}-container-executor"
    enabled: true
    runlevel: default

