---
- name: "Ensure {{ podman_user }} is created and locked to prevent logins on the user"
  ansible.builtin.user:
    name: "{{ podman_user }}"
    create_home: true
    home: "{{ podman_user_home }}"
    password_lock: true
    state: present

- name: "Check {{ podman_user }} user linger status"
  ansible.builtin.stat:
    path: "/var/lib/systemd/linger/{{ podman_user }}"
  register: user_lingering

- name: "Ensure lingering for {{ podman_user }} is enabled to enure podman is still running after logout due to script execution termination"
  ansible.builtin.command: "loginctl enable-linger {{ podman_user }}"
  # Lingering does not work when executed in a docker environment. It is also not needed, as the container will be
  # destroyed after execution.
  when: not user_lingering.stat.exists and ansible_connection != "docker"

- name: Ensure systemd directory and user subdirectory exists
  ansible.builtin.file:
    path: "{{ podman_user_systemd_directory }}"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
    mode: 0755

- name: Ensure podman tmp file storage environment variable is exported in .bashrc
  ansible.builtin.lineinfile:
    path: "{{ podman_user_home }}/.bashrc"
    regexp: '^export XDG_RUNTIME_DIR'
    line: 'export XDG_RUNTIME_DIR=/run/user/"$(id -u)"'
    state: present
    insertafter: EOF
