Vagrant.configure("2") do |config|
  staging_environments = [
    {
      :environment => "dev",
      :ssh_port => "10022",
    }
  ]

  staging_environments.each do |env|
    config.vm.define env[:environment] do |env_config|
      env_config.vm.box = "generic/alpine319"
      env_config.vm.box_version = "4.3.12"
      env_config.vm.hostname = env[:environment]
      env_config.vm.network :forwarded_port, guest: 22, host: env[:ssh_port], id: "ssh"
      env_config.vm.network :forwarded_port, guest: 20000, host: 20000, id: "immich"

      env_config.vm.provider do |v|
        v.memory = 8192
        v.cpus = 4

      env_config.vm.provision "shell", inline: <<-SHELL
        echo "Installing required packages..."
        sudo apk update
        sudo apk add --no-cache \
          python3
      SHELL

      env_config.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "../../deploy.yaml"
        ansible.become = true # start ansible script with sudo and let the playbook handle privilege changes from there.
        ansible.groups = { 
          "deployserver" => [ env[:environment] ],
          "configserver" => [ "localhost" ],
          "configserver:vars" => { "ansible_connection" => "local" }
        }
        ansible.extra_vars = "../../vars/#{env[:environment]}.yaml"
      end
    end
  end
end
