---
apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: photoprism
type: Opaque
stringData:
  adminPassword: admin
  dbPassword: photoprism-db-password
  dbRootPassword: photoprism-db-root-password
