---
- name: Ensure firewall is installed
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - ip6tables
    - iptables
    - awall

- name: Ensure awall policy is available
  ansible.builtin.copy:
    src: global-policy.json
    dest: /etc/awall/optional/

- name: Ensure awall port redirect config and policy are enabled
  community.general.awall:
    name: global-policy
    state: enabled
  loop:

- name: Ensure awall policies are well defined
  ansible.builtin.command: "awall translate -o /tmp"

- name: Ensure awall policies are active
  community.general.awall:
    activate: true
  async: 3
  poll: 0
  become: true
  become_method: "{{ superuser_method }}"

- name: Sleep to avoid ssh issues due to the awall policy application
  ansible.builtin.pause:
    seconds: 3

- name: Ensure iptables is enabled in default runlevel
  ansible.builtin.service:
    name: iptables
    state: started
    enabled: true
    runlevel: default

- name: Ensure firewall rules stay persisted after system restart
  ansible.builtin.command: rc-service iptables save

