#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

echo "Install python"
sudo DEBIAN_FRONTEND=noninteractive apt -y \
  -o Dpkg::Options::="--force-confdef" \
  -o Dpkg::Options::="--force-confold" install \
  python3

