#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

echo "Upgrade all installed packages including the kernel"
sudo apt update
sudo DEBIAN_FRONTEND=noninteractive apt -y \
  -o Dpkg::Options::="--force-confdef" \
  -o Dpkg::Options::="--force-confold" upgrade

