apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: dashboard-secret
    namespace: traefik
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: dashboard-secret
          stringData:
            #ENC[AES256_GCM,data:yNgT8WNwnlmWSGo9xZndRqwuHvaL8vJI1JO256E2LheEiCnq2kB3TbVU7g==,iv:s940lT27KM2u3t7hnJEfaYJ50Bvoyv3m8dDTf+nkNq0=,tag:yxvahvL7cHHRKF0IA6G51w==,type:comment]
            users: ENC[AES256_GCM,data:9gY3O0rN6YZm5P2i1oJ4Z7vYATedykdI70uuIB9b+x3Ob9E8yfXFnHGlA5d2vuDQKD0MA9vE1UsbTTP22XYeMVBY,iv:a8HrmvA+8hRS2fgzJzo0BBgV9dR4093+MkUy9n/zkVs=,tag:nKsAHHwdnSpAHOVoPSZTkA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITGFEbEl0RnNYQmloRi9H
            WmFOaURQS010dGc2amVoVkxUSDFEd29uR21zCktTdFp2VG9FS2p5WFZNb1RHRER5
            VHNQSUJiV3R0cEpwN0VoOTBnVDVXQ2MKLS0tICtiZWVubVFNUk9Ebnd1SFBIWm1S
            bVR4bUJIeHFwRmdBOTVnOEJXTHlBUFUKezGqLVZPhRNiB0q8dSRkslD6MvY2k8Lf
            p7ntc73/cAgMpKj2N2vTgsjMXvfZVX6jFPKaAFW9yn2nfbCMrJ8Pxg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wxuxlngq2cf4jsxfw5v2cwd0p8jxwqkjxvy0vhsmg9wuktey0vcs7q79zx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T21:47:23Z"
    mac: ENC[AES256_GCM,data:GFotiUZzCmYMA7YAp4nI7EPD7vRB7y1sKdeaoNfvqRGHjC98CbJ6EVBY3rAtZOZ3DmQ7+wbmnf92korqmCbqD8vdNxxhZw2L6akmnKxe73aAxkC1Aly2p5K2CQ2XQH+/mvW593cEmZV64C4by+e7JuGdT1W5SJM2XDAGUmev0iM=,iv:2QE8vfEDpzazU0yeezHGoIxGF4JI3I97BRaIwJ6ur9M=,tag:u85+/EfzK0PSxwOreuStIw==,type:str]
    version: 3.13.1
