---
apiVersion: v1
kind: Secret
metadata:
  name: dashboard-secret
  namespace: traefik
type: Opaque
stringData:
  # htpasswd format (user:bcrypt-hash). Dev creds: admin / admin.
  users: |
    admin:$2b$10$FI5cbH6WWk5zwI9cxZIqZ.RAx.X2rquZOXNMMcrCxeN34J7I7iVOK
