---
- name: Ensure Debian ETH Zurich sources are present
  ansible.builtin.deb822_repository:
    name: debian-ethz
    types: deb
    uris: https://debian.ethz.ch/debian
    suites: "{{ ansible_facts['distribution_release'] }}"
    components:
      - main
      - contrib
      - non-free
    state: present

- name: Ensure Debian Init7 mirror sources are present
  ansible.builtin.deb822_repository:
    name: debian-init7
    types: deb
    uris: https://mirror.init7.net/debian
    suites: "{{ ansible_facts['distribution_release'] }}"
    components:
      - main
      - contrib
      - non-free
    state: present

- name: Ensure no default package sources are configured
  ansible.builtin.copy:
    dest: /etc/apt/sources.list
    content: ""
    owner: root
    group: root
    mode: 0644

- name: Ensure apt cache is updated
  ansible.builtin.apt:
    update_cache: true

