---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mosquitto-netpol-egress
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      connectsToMqtt: "true"
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: mosquitto
      ports:
        - protocol: TCP
          port: {{ .Values.mosquitto.port }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mosquitto-netpol-ingress
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: mosquitto
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              connectsToMqtt: "true"
      ports:
        - protocol: TCP
          port: {{ .Values.mosquitto.port }}
