---
apiVersion: v1
kind: Service
metadata:
  name: zigbee2mqtt
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: zigbee2mqtt
  ports:
    - port: {{ .Values.zigbee2mqtt.port }}
      targetPort: {{ .Values.zigbee2mqtt.port }}
