---
services:
  immich:
    node: k3d-homelab-dev-cluster-server-0
    path: /tmp/service-data/immich-storage
  kimai:
    node: k3d-homelab-dev-cluster-server-0
    path: /tmp/service-data/kimai-storage
  homeassistant:
    node: k3d-homelab-dev-cluster-server-0
    path: /tmp/service-data/homeassistant-storage

