---
services:
  immich:
    node: charon
    path: /service-data/immich-storage
  kimai:
    node: daisy
    path: /mnt/data/kimai-storage
  filebrowser:
    node: charon
    path: /service-data/filebrowser-storage

