---
services:
  immich:
    node: charon
    path: /service-data/immich-storage
  kimai:
    node: daisy
    path: /mnt/data/kimai-storage
  homeassistant:
    node: daisy
    path: /mnt/data/homeassistant-storage

