---
services:
  immich:
    node: charon
    path: /service-data/immich-storage
  kimai:
    node: daisy
    path: /mnt/data/kimai-storage
  karakeep:
    node: daisy
    path: /mnt/data/karakeep-storage

