apiVersion: v1
kind: Secret
metadata:
    name: sops-age-key
    namespace: sops-secrets-operator
type: Opaque
stringData:
    key: ENC[AES256_GCM,data:M6YoL2TIlMYpRw4Y4EE2mV2/Y7gi6YMobtEIXIC4HZnOzmNP1LdKAfuCXaeul6DruLRNT78OnN2YsSin0oBm4zgMAvNEluQMRaE=,iv:9F5Bg2LO02HhKZiziNcZJnH4w/Bz5xfjV8dZL6EnNWk=,tag:TR6cxoZTNqioinfu8k8DBw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPU1JlblVUOStkTzFWb2Fl
            dVBkMkFOYTJ3dnNvV1dNaWxkWU5UR1pqQnhZCndKdXlsSitORFBGNm5vejZnRkJH
            T2lvc0E2a1NDaXpuNTRSSW4zWkp4MFkKLS0tIFR3SW9JajB5U1BYdVFHUXhsOTdS
            Q3pTYUxZa3p5WlFXbFN3N2pockQ0S1UKlMA9oyhJbBAoyrZwZIvxKkaI63EhFGnx
            ErLjD2ByL5xwWsykzN7s0ebNwnM+BsJMhw/FFy2uMeS2s2eDDDUraA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wxuxlngq2cf4jsxfw5v2cwd0p8jxwqkjxvy0vhsmg9wuktey0vcs7q79zx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T23:03:44Z"
    mac: ENC[AES256_GCM,data:F/SAC35rRzRm7JG1RrzZXRqrqFyKH/f3vsU7akOPSd9NLpVcOiPkZ9HZFFtenzVRESLCwFdZz5LYDvhzfjQeseqTUGYDPK06xhpnuJyo4TRAUc9ZQhoRC45ox/gc7NShon22spQHutDXpJV1BjekVkiHnQfQ6euIDLR7tcq4kCg=,iv:Sps1QZEChs3ffpHhCJ+L6D/bBrQE+UMI0iyhJN45Er4=,tag:RyKERJizNwJgG6lYNjfrpA==,type:str]
    version: 3.13.1
