apiVersion: v1
kind: Secret
metadata:
    name: sops-age-key
    namespace: sops-secrets-operator
type: Opaque
stringData:
    key: ENC[AES256_GCM,data:I/IxCMgep9/evOWvNl698QwyMzntmwSy0bq9zu43BmAgpyJsqvUjETlo7h7VmoVk+JOJuORWnOH8CrmYfIqDFFFFtEULsDdBWB8=,iv:7k86zo4Z8Wju/hQwtU2jRbphvnjw8115B5UeLZ2RL+k=,tag:xxJkOAB+BZhSzVAPXzEoww==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcFNDc0dpN1BxVmhnOW9j
            NDhCWWtXa0JXUmcyS3ROcnFRWjJ0aEdUTzBjCi9GNk5FUHBzdkpZZ0tZNTJid2RE
            cm1uSnpHS21ZSWp2SjJJQzB2bHZMQlUKLS0tIHhzZU5LL0pxem5lekVYdXNWQUpU
            U3EzbDdYaHZWYkhuV3VwOUF2YldjOFEKTiAv8bsTS29YifIXwAWcFK4ohxEhKQZn
            /9LkBrMgEapLTr0zpCxZMBretet14VdCRFBNcqCmF3oOXoBzEWo3NA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cek8pae0a8mvptlwcfnhahkaqlyu7u8stg48uncexvf24trg9pgqs5pehk
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T23:04:14Z"
    mac: ENC[AES256_GCM,data:QUsqa7EhB5+K+sxU0HDEqN9sbeOAi62NE5O9SKdbTBFYl1RihSIf/wPnDZK7tq2eeAqjYh0xFYc2bfzqmgKs63ko7ca5AlQ+ZazfIE1QRvcIOwQMmn+/j0Gr3/puOjhyA+57fRdG3wojzDZwuYv+CcQGx5P/7wKLC0SvaPEzLRk=,iv:oEIUHHcnGVRuSM57X0xVa79kKVTMDcVt7bmTzpCNfjY=,tag:GKCSsIdSiyMNvbVB0dwXww==,type:str]
    version: 3.13.1
