---
- name: Ensure immich upload location exists
  ansible.builtin.file:
    path: "{{ immich_upload_location }}"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
    mode: 0644

- name: Ensure immich-server systemd service is stopped
  ansible.builtin.systemd:
    scope: user
    name: "container-immich-server.service"
    enabled: no
    state: stopped
  register: "result_immich_server_stop"
  failed_when: "result_immich_server_stop is failed and 'Could not find the requested service' not in result_immich_server_stop.msg"

- name: Ensure immich-server container is removed
  containers.podman.podman_container:
    name: immich-server
    state: absent

- name: "Ensure getent_passwd variable is setup"
  ansible.builtin.getent:
    database: passwd
    key: "{{ podman_user }}"

- name: "Ensure {{ podman_user }} id is retrieved"
  ansible.builtin.set_fact:
    podman_user_id: "{{ getent_passwd[podman_user].1 }}"

- name: Pull immich-server image
  containers.podman.podman_image:
    name: "{{ immich_server_image }}"
    force: true

- name: Ensure immich-server container is created
  containers.podman.podman_container:
    name: immich-server
    hostname: "immich-server-{{ ansible_hostname }}"
    image: "{{ immich_server_image }}"
    user: "{{ podman_user_id }}"
    userns: keep-id
    recreate: no
    state: created
    env:
      - DB_DATABASE_NAME: "{{ immich_db_database_name }}"
      - DB_USERNAME: "{{ immich_db_username }}"
      - DB_PASSWORD: "{{ immich_db_password }}"
    volumes:
      - "{{ immich_upload_location }}:/usr/src/app/upload"
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "{{ immich_server_port }}:2283"
    network:
      - immich_network
    network_aliases:
      - immich-server
    generate_systemd:
      path: "{{ podman_user_systemd_directory }}"
      names: true

- name: Ensure immich-server systemd service is activated
  ansible.builtin.systemd:
    scope: user
    name: "container-immich-server.service"
    enabled: yes
    daemon_reload: yes
    state: started

- name: Wait for immich-server to be healthy
  ansible.builtin.uri:
    url: "https://{{ container_host }}:{{ immich_server_port }}"
    status_code: 200
    validate_certs: false
  register: result
  until: result.status == 200
  retries: 30
  delay: 2

