---
- name: Ensure immich upload location exists
  ansible.builtin.file:
    path: "{{ immich_upload_location }}"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
    mode: 0755
    recurse: true

- name: asdf
  command: echo $CONTAINER_HOST
  register: container_host_output

- debug: msg="{{ container_host_output }}"

- name: Instantiate immich-server container
  ansible.builtin.include_role:
    name: infrastructure/container
  vars:
    container_name: immich-server
    container_image: "{{ immich_server_image }}"
    container_image_tag: "{{ immich_server_tag }}"
    container_env:
      DB_DATABASE_NAME: "{{ immich_db_database_name }}"
      DB_USERNAME: "{{ immich_db_username }}"
      DB_PASSWORD: "{{ immich_db_password }}"
    container_volumes:
      - "{{ immich_upload_location }}:/usr/src/app/upload"
      - /etc/localtime:/etc/localtime:ro
    container_ports:
      - "{{ immich_server_port }}:2283"
    container_networks:
      - "{{ immich_network }}"
    container_network_aliases:
      - immich-server
    container_user: "{{ podman_user }}"
    container_user_systemd_directory: "{{ podman_user_systemd_directory }}"

- name: Wait for immich-server to be healthy
  ansible.builtin.uri:
    url: "https://{{ container_host }}:{{ immich_server_port }}"
    status_code: 200
    validate_certs: false
  register: result
  until: result.status == 200
  retries: 30
  delay: 2

