---
- name: Ensure immich storage directory location exists
  ansible.builtin.file:
    path: "{{ immich_storage_directory }}"
    state: directory
    owner: "{{ podman_user }}"
    group: "{{ podman_user }}"
    mode: 0755
  # Not possible in staging environments, as the filesystem used by podman is that of the host, not of the container
  when: ansible_connection != "docker"

- name: Ensure immich container network is created
  containers.podman.podman_network:
    name: immich_network
    driver: bridge
    recreate: false
    state: present

- include_tasks: immich-database.yaml
- include_tasks: immich-redis.yaml
- include_tasks: immich-machine-learning.yaml
- include_tasks: immich-server.yaml

