---
- name: "Ensure {{ podman_user }} is created"
  ansible.builtin.include_role:
    name: infrastructure/user
  vars:
    user_name: "{{ podman_user }}"
    user_password: "{{ podman_user_password }}"

- name: Ensure immich is running
  become: true
  become_user: "{{ podman_user }}"
  block:
    - name: Ensure immich storage directory location exists
      ansible.builtin.file:
        path: "{{ immich_storage_directory }}"
        state: directory
        owner: "{{ podman_user }}"
        group: "{{ podman_user }}"
        mode: 0755

    - name: Ensure immich container network is created
      containers.podman.podman_network:
        name: immich_network
        driver: bridge
        recreate: false
        state: present

    - include_tasks: immich-database.yaml
    - include_tasks: immich-redis.yaml
    - include_tasks: immich-machine-learning.yaml
    - include_tasks: immich-server.yaml

