---
- name: Ensure tailscale is installed
  ansible.builtin.package:
    name: tailscale
    state: present

- name: Ensure tailscale service is enabled and started
  ansible.builtin.service:
    name: tailscale
    enabled: true
    state: started

