---
- name: Ensure zigbee2mqtt config location exists
  ansible.builtin.file:
    path: "{{ homeassistant_zigbee2mqtt_config_location }}"
    state: directory
    owner: "{{ homeassistant_user }}"
    group: "{{ homeassistant_user }}"
    mode: 0755
    recurse: true

- name: Ensure zigbee2mqtt config exists
  ansible.builtin.template:
    dest: "{{ homeassistant_zigbee2mqtt_config_location }}/configuration.yaml"
    src: zigbee2mqtt/configuration.yaml.j2
    owner: "{{ homeassistant_user }}"
    group: "{{ homeassistant_user }}"
    mode: 0600

- name: Ensure treafik is configured for zigbee2mqtt
  ansible.builtin.include_role:
    name: infrastructure/traefik-service
  vars:
    service_name: zigbee2mqtt
    service_port: "{{ homeassistant_zigbee2mqtt_port }}"

- name: "Ensure {{ homeassistant_user }} is the owner of the zigbee adapter device"
  ansible.builtin.file:
    path: "{{ homeassistant_zigbee2mqtt_zigbee_device_id }}"
    owner: "{{ homeassistant_user }}"
    group: "{{ homeassistant_user }}"
  become: true
  become_method: "{{ superuser_method }}"

- name: Instantiate zigbee2mqtt container
  ansible.builtin.include_role:
    name: infrastructure/container
  vars:
    container_name: zigbee2mqtt
    container_image: "{{ homeassistant_zigbee2mqtt_image }}"
    container_image_tag: "{{ homeassistant_zigbee2mqtt_tag }}"
    container_env:
      TZ: Europe/Zurich
      ZIGBEE2MQTT_CONFIG_FRONTEND_AUTH_TOKEN: "{{ homeassistant_zigbee2mqtt_frontend_auth_token }}"
      ZIGBEE2MQTT_CONFIG_MQTT_USER: "{{ homeassistant_mosquitto_zigbee2mqtt_username }}"
      ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: "{{ homeassistant_mosquitto_zigbee2mqtt_password }}"
    container_volumes:
      - "{{ homeassistant_zigbee2mqtt_config_location }}:/app/data:rw"
      - "/run/udev:/run/udev:ro"
    container_ports:
      - "{{ homeassistant_zigbee2mqtt_port }}:8080"
    container_device:
      - "{{ homeassistant_zigbee2mqtt_zigbee_device_id }}:/dev/ttyUSB0"
    container_networks:
      - "{{ homeassistant_network }}"
    container_network_aliases:
      - zigbee2mqtt
    container_user: "{{ homeassistant_user }}"

- ansible.builtin.include_role:
    name: infrastructure/http-healthcheck
  vars:
    service_name: zigbee2mqtt
    service_port: "{{ homeassistant_zigbee2mqtt_port }}"
  tags:
    # zigbee2mqtt checks if the device provided to the container exists and fails otherwise.
    # As we do not have a dummy device for dev testing, this task has to be skipped. It is
    # also not possible to test mqtt communication between HA and Z2M.
    - prod-only

