---
- name: Ensure timezone data (tzdata) is installed
  ansible.builtin.package:
    name: tzdata
    state: present

- name: Ensure timezone is configured correctly
  ansible.builtin.file:
    src: /usr/share/zoneinfo/Europe/Zurich
    dest: /etc/localtime
    state: link

- name: Ensure podman is installed
  ansible.builtin.package:
    name: podman
    state: present

- name: Ensure acl is installed to allow for ansible to perform user switching to unprivileged user
  ansible.builtin.package:
    name: acl
    state: present

