---
- name: Ensure nextcloud data and config location exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nextcloud_user }}"
    group: "{{ nextcloud_user }}"
    mode: 0755
    recurse: true
  loop:
    - "{{ nextcloud_config_location }}"
    - "{{ nextcloud_data_location }}"

- name: Instantiate nextcloud-app container
  ansible.builtin.include_role:
    name: infrastructure/container
  vars:
    container_name: nextcloud_app
    container_image: "{{ nextcloud_app_image }}"
    container_image_tag: "{{ nextcloud_app_tag }}"
    container_env:
      POSTGRES_HOST: database
      POSTGRES_DB: "{{ nextcloud_db_database_name }}"
      POSTGRES_USER: "{{ nextcloud_db_username }}"
      POSTGRES_PASSWORD: "{{ nextcloud_db_password }}"
      # TODO: Activate once https://github.com/nextcloud/docker/issues/763 is fixed
      # REDIS_HOST: redis
      NEXTCLOUD_ADMIN_USER: "{{ nextcloud_admin_username }}"
      NEXTCLOUD_ADMIN_PASSWORD: "{{ nextcloud_admin_password }}"
    container_volumes:
      - "{{ nextcloud_config_location }}:/var/www/html:rw"
      - "{{ nextcloud_data_location }}:/var/lib/nextcloud:rw"
    container_ports:
      - "{{ nextcloud_app_port }}:80"
    container_networks:
      - "{{ nextcloud_network }}"
    container_network_aliases:
      - nextcloud-app
    container_user: "{{ nextcloud_user }}"

- name: Ensure nextcloud data location exists in container
  containers.podman.podman_container_exec:
    name: nextcloud_app
    user: root
    command: "bash -c 'mkdir -p /var/lib/nextcloud && chown -R www-data:www-data /var/lib/nextcloud && chmod 750 /var/lib/nextcloud'"

- name: Ensure nextcloud is properly configured
  containers.podman.podman_container_exec:
    name: nextcloud_app
    user: www-data
    command: "php occ maintenance:install --data-dir /var/lib/nextcloud"

- name: Wait for nextcloud-app to be healthy
  ansible.builtin.uri:
    # TODO: change to https
    url: "http://localhost:{{ nextcloud_app_port }}"
    status_code: 200
    validate_certs: false
  register: result
  until: result.status == 200
  retries: 30
  delay: 2

