---
superuser_method: sudo

# Traefik
traefik_user_password: "$6$rVOhw/ClrcbnLo6y$xZexCAxW8Uttz57SBfusvBG0NBLXrughO6L5hYP8DqJ7XINtvpAMnM78Iej9/45E5h7ZQofQaEI1yE6vlt18A/" # this is 123456

# Immich
immich_user_password: "$6$rVOhw/ClrcbnLo6y$xZexCAxW8Uttz57SBfusvBG0NBLXrughO6L5hYP8DqJ7XINtvpAMnM78Iej9/45E5h7ZQofQaEI1yE6vlt18A/" # this is 123456
immich_db_password: immich-db-password

# Nextcloud
nextcloud_user_password: "$6$rVOhw/ClrcbnLo6y$xZexCAxW8Uttz57SBfusvBG0NBLXrughO6L5hYP8DqJ7XINtvpAMnM78Iej9/45E5h7ZQofQaEI1yE6vlt18A/" # this is 123456
nextcloud_db_password: nextcloud-db-password
nextcloud_admin_username: admin
nextcloud_admin_password: admin
nextcloud_user_default_password: default_password1*
nextcloud_user_definitions:
  - username: test_user1
    display_name: "Test User 1"
  - username: test_user2
    display_name: "Test User 2"

# PhotoPrism
photoprism_user_password: "$6$rVOhw/ClrcbnLo6y$xZexCAxW8Uttz57SBfusvBG0NBLXrughO6L5hYP8DqJ7XINtvpAMnM78Iej9/45E5h7ZQofQaEI1yE6vlt18A/" # this is 123456
photoprism_db_password: photoprism-db-password
photoprism_db_root_password: photoprism-db-root-password
photoprism_admin_username: admin # PhotoPrism does not allow to create users in the free version. This is also the user to use the application with.
photoprism_admin_password: admin
