apiVersion: v1
kind: Secret
metadata:
    name: my-secret
stringData:
    TEST: ENC[AES256_GCM,data:v8x1oXSCobr3xME=,iv:fGp2NdufT0+ndW2o8rvJMddfpu7hTMB7l4r6e7SwB0o=,tag:HImAfMzmtxilUsbf/+q+ug==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiT1hLYmVWcEk2YlFKL2oz
            MU9MUnZFSW44c2FGVTdjcjNlaHVrOTAzZUNBCjBBWVJ1UTZuVEx0YzdiZVlhME5U
            ajRPc2xuc0x4aG1zR2grNE9GZGlkdmMKLS0tIGhnWkY1VnhWRGtGeE1zZXNmRndu
            eUpFcHFGbUpJTFpRaE9kdXM1NFJlU3MK+uMdSw1+jnmD4Q/4LjZDCH2q3T4JdI7h
            DPNQMomr8ReNEExEDCim3MY79iHKu9xzku/PHK+jYUhs8iPZ4Ul6eA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wxuxlngq2cf4jsxfw5v2cwd0p8jxwqkjxvy0vhsmg9wuktey0vcs7q79zx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T22:46:46Z"
    mac: ENC[AES256_GCM,data:WLWsyk6atWmpD6iedZIGp51CdT4gnp8M0CE7MnaiXN5Fy8oCOYB35X5XvkUgqeQUuc+bE3nU8EJg6oAoTBFHPB4k59aKYF56gAV5x/TRfhH2WszgB0RFp2MsyTYapMMn9g0dctN+Xzvv4F+1iVCTBwQY0DbQUtT2SUWdY9g6UFY=,iv:QBeJUm04DQO3X2iB/E5RterZMFc/tzGU4CTTaQ5ep70=,tag:hQNsJiS11arFmrmHljk1PQ==,type:str]
    version: 3.13.1
