apiVersion: v1
kind: Secret
metadata:
    namespace: homelab
    name: nginx-secret
stringData:
    TEST: ENC[AES256_GCM,data:v8x1oXSCobr3xME=,iv:fGp2NdufT0+ndW2o8rvJMddfpu7hTMB7l4r6e7SwB0o=,tag:HImAfMzmtxilUsbf/+q+ug==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiT1hLYmVWcEk2YlFKL2oz
            MU9MUnZFSW44c2FGVTdjcjNlaHVrOTAzZUNBCjBBWVJ1UTZuVEx0YzdiZVlhME5U
            ajRPc2xuc0x4aG1zR2grNE9GZGlkdmMKLS0tIGhnWkY1VnhWRGtGeE1zZXNmRndu
            eUpFcHFGbUpJTFpRaE9kdXM1NFJlU3MK+uMdSw1+jnmD4Q/4LjZDCH2q3T4JdI7h
            DPNQMomr8ReNEExEDCim3MY79iHKu9xzku/PHK+jYUhs8iPZ4Ul6eA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wxuxlngq2cf4jsxfw5v2cwd0p8jxwqkjxvy0vhsmg9wuktey0vcs7q79zx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-09T23:10:04Z"
    mac: ENC[AES256_GCM,data:zF+4IA+dt8i0qbEx3U1LcLyGP556mBebWMlYX0N6MRNzyrMipYo+Eusb26WKkOkaUCvbsarzSMBh3rLQZ/tyrUvUddkSL8TK94dYUijpnl7ERGcWhFu2wi8vv6O60x4Y4PN4H2z6uilSipO6Dwji36/4Oxf1PmhxsnFcvSqv5zk=,iv:DPCxWcmaA/XFxuGUwtGEKqDw1gYiAA3TAj1OF8YEow0=,tag:N4V8HPFJmfSbMZimbddVUA==,type:str]
    version: 3.13.1
