---
- name: Ensure firewall is installed
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - ip6tables
    - iptables
    - awall

- name: Ensure awall service policy are available
  ansible.builtin.copy:
    src: global-policy.json
    dest: /etc/awall/optional/

- name: Ensure awall service configs are available
  ansible.builtin.template:
    src: service.json.j2
    dest: "/etc/awall/optional/{{ item.service_name }}.json"
  loop:
    - service_name: traefik
      service_port: "{{ traefik_dashboard_port }}"
    - service_name: immich
      service_port: "{{ immich_server_port }}"
    - service_name: nextcloud
      service_port: "{{ nextcloud_server_port }}"
    - service_name: photoprism
      service_port: "{{ photoprism_server_port }}"

- name: Ensure awall service config and policy are enabled
  community.general.awall:
    name: "{{ item }}"
    state: enabled
  loop:
    - global-policy
    - traefik
    - immich
    - nextcloud
    - photoprism

- name: Ensure iptables services are started, such that the awall activation will succeed
  ansible.builtin.command: "iptables -L"
  become: true
  become_method: "{{ superuser_method }}"

- name: Ensure ip6tables services are started, such that the awall activation will succeed
  ansible.builtin.command: "ip6tables -L"
  become: true
  become_method: "{{ superuser_method }}"

- name: Ensure awall policies are active
  ansible.builtin.command: "awall activate -f"
  async: 5
  poll: 0
  become: true
  become_method: "{{ superuser_method }}"

- name: Sleep to avoid ssh issues due to the awall policy application
  ansible.builtin.pause:
    seconds: 5

