---
- name: Ensure firewall is installed
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - ip6tables
    - iptables
    - awall

- name: Ensure awall policy and traefik configs are available
  ansible.builtin.copy:
    src: global-policy.json
    dest: /etc/awall/optional/

- name: Ensure traefik configs is available
  ansible.builtin.template:
    src: traefik.json.j2
    dest: /etc/awall/optional/traefik.json

- name: Ensure awall service config and policy are enabled
  community.general.awall:
    name: "{{ item }}"
    state: enabled
  loop:
    - global-policy
    - traefik

- name: Ensure awall policies are well defined
  ansible.builtin.command: "awall translate -o /tmp"

- name: Ensure awall policies are active
  community.general.awall:
    activate: true
  async: 3
  poll: 0
  become: true
  become_method: "{{ superuser_method }}"

- name: Sleep to avoid ssh issues due to the awall policy application
  ansible.builtin.pause:
    seconds: 3

