---
domain: dev.homelab.mikemarti.ch

# Traefik
traefik_user_password: "123456"
traefik_ca_server: "https://acme-staging-v02.api.letsencrypt.org/directory"
traefik_dashboard_username: admin
traefik_dashboard_password: admin

