---
domain: dev.homelab.mikemarti.ch
platform: alpine
processor_microcode_package: intel-ucode
superuser_method: sudo

# Traefik
traefik_user_password: "123456"
traefik_ca_server: "https://acme-staging-v02.api.letsencrypt.org/directory"
traefik_dashboard_username: admin
traefik_dashboard_password: admin

# Immich
immich_user_password: "123456"
immich_db_password: immich-db-password

# Filebrowser
filebrowser_user_password: "123456"
filebrowser_admin_username: admin
filebrowser_admin_password: adminadmin123*

# PhotoPrism
photoprism_user_password: "123456"
photoprism_db_password: photoprism-db-password
photoprism_db_root_password: photoprism-db-root-password
photoprism_admin_username: admin # PhotoPrism does not allow to create users in the free version. This is also the user to use the application with.
photoprism_admin_password: admin

# Gitea
gitea_user_password: "123456"
gitea_db_password: gitea-db-password

