apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: secret
    namespace: immich
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: secret
          stringData:
            dbPassword: ENC[AES256_GCM,data:HMl2atVm8xZFRGFqN5IeVC+6IaROEtzugo/DS9CYiyE=,iv:BfcD8nQrWd+TTFLACGFWmECPk1DZuAF9CHav5S6d3/Y=,tag:M+UX8FxzJun9k2vouihoEA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQTByOVJUeEpqUGREZzh5
            RTcvR3QwNFd4bllUeHRiWlNVWGgzN2ZncjFVCjZONWhsbnNJdlkxM3lDWkJ5aVA3
            cmFWZTN0UlpxWXl4OVN0bE1UcGlKOEUKLS0tIC9jaGw0Z3gxampydjBmbVorL3p2
            WDlaYk56ZDEzOEpwOTY1WTZPbDNvYUEKywgy3ewpDdjcLGUBrB7nf856mVaTw8WI
            WK+GsWH8vgbdc+wvbY5MPYi8ozcRB+xtz1rzzzlSY01mD8fTW4xA3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wxuxlngq2cf4jsxfw5v2cwd0p8jxwqkjxvy0vhsmg9wuktey0vcs7q79zx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T19:05:15Z"
    mac: ENC[AES256_GCM,data:WA7T6vd4Ecp7y5HVHMSAL+lnsetc7xotqv5qWQHX6PG7aD2z3UBArqTBQmwmFIIj8fTkMNYdSJ1ecgAhZ5NPTuOiEWHqZJYfxEyxPNd4v3Lwdl6L9Egcg8tFt8xNqWL4rd4wfdla/xN4VRdhOkEMxl+wRm7BqeiW35d9BmzSmK4=,iv:2uaxBR72xA3+R8UGYu8rjrz5wj/vIWgNUIzZ0qA1IAY=,tag:yOWK5O/V0Nv8n4sIM1OoNg==,type:str]
    version: 3.13.1
