---
- name: Ensure script to easily reset the firewall is available (in case something goes wrong)
  ansible.builtin.copy:
    dest: "/home/{{ ansible_user }}/firewall-reset.sh"
    content: |
      #!/bin/sh
      {{ superuser_method }} iptables -F
      {{ superuser_method }} iptables -t nat -F
      {{ superuser_method }} iptables -t mangle -F
      {{ superuser_method }} iptables -X
      {{ superuser_method }} iptables -t nat -X
      {{ superuser_method }} iptables -t mangle -X
      {{ superuser_method }} iptables -P INPUT ACCEPT
      {{ superuser_method }} iptables -P FORWARD ACCEPT
      {{ superuser_method }} iptables -P OUTPUT ACCEPT
      {{ superuser_method }} ip6tables -F
      {{ superuser_method }} ip6tables -t nat -F
      {{ superuser_method }} ip6tables -t mangle -F
      {{ superuser_method }} ip6tables -X
      {{ superuser_method }} ip6tables -t nat -X
      {{ superuser_method }} ip6tables -t mangle -X
      {{ superuser_method }} ip6tables -P INPUT ACCEPT
      {{ superuser_method }} ip6tables -P FORWARD ACCEPT
      {{ superuser_method }} ip6tables -P OUTPUT ACCEPT
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Ensure ufw is installed
  ansible.builtin.package:
    name: "ufw"
    state: present

- name: Ensure incoming and routed traffic is denied by default
  community.general.ufw:
    default: deny
    direction: "{{ item }}"
  loop:
    - incoming
    - routed

- name: Ensure outgoing traffic is allowed by default
  community.general.ufw:
    default: allow
    direction: outgoing

- name: Ensure NAT rules are present in ufw manual configuration
  ansible.builtin.blockinfile:
    path: /etc/ufw/before.rules
    marker: "# {mark} ANSIBLE NAT RULES"
    block: |
      *nat
      :PREROUTING ACCEPT [0:0]
      :OUTPUT ACCEPT [0:0]
      :POSTROUTING ACCEPT [0:0]

      # NAT_RULE_MARKER

      COMMIT
    insertbefore: BOF
    create: false

- name: Ensure ssh connection is allowed
  community.general.ufw:
    rule: allow
    port: ssh
    proto: tcp

- name: Ensure ufw rules are running and reloaded on boot
  community.general.ufw:
    state: enabled
  async: 3
  poll: 0

