---
- name: "Ensure {{ container_name }} container is removed"
  containers.podman.podman_container:
    name: "{{ container_name }}"
    state: absent

- name: "Ensure getent_passwd variable is setup"
  ansible.builtin.getent:
    database: passwd
    key: "{{ container_user }}"

- name: "Ensure {{ container_user }} id is retrieved"
  ansible.builtin.set_fact:
    container_user_id: "{{ getent_passwd[container_user].1 }}"

- name: "Pull {{ container_name }} image"
  containers.podman.podman_image:
    name: "{{ container_image }}:{{ container_image_tag }}"
    force: true

- name: "Ensure {{ container_name }} container is created"
  containers.podman.podman_container:
    name: "{{ container_name }}"
    hostname: "{{ container_name }}"
    image: "{{ container_image }}:{{ container_image_tag }}"
    user: "{{ container_user_id }}"
    userns: keep-id
    recreate: false
    restart_policy: on-failure
    state: started
    env: "{{ container_env }}"
    volumes: "{{ container_volumes }}"
    ports: "{{ container_ports }}"
    network: "{{ container_networks }}"
    network_aliases: "{{ container_network_aliases | default(omit) }}" # Cannot set alias in host network mode => used by traefik
    command: "{{ container_command | default(omit) }}"

- name: "Ensure {{ container_name }} is started after reboot of host by adding it to s6 run script"
  ansible.builtin.lineinfile:
    path: "/home/{{ container_user }}/s6-services/container-autostart/run"
    line: "exec podman start -a {{ container_name }}"
    insertafter: EOF
    owner: "{{ container_user }}"
    group: "{{ container_user }}"
    mode: 0755

