apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: digitalocean-dns-credentials
    namespace: cert-manager
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: digitalocean-dns-credentials
          stringData:
            api-token: ENC[AES256_GCM,data:dHK++Yl8aGB5+gZwJ2nzyGS61zbOkNlmsbnneQ2XdOfHNYheYxT8VHVauugLRLJoYWAkT2Ru1ieEcE4ay0sEcSxPB8/ZSTg=,iv:Xrt9Dm5GY+RaA1EOzz5xf8hsp7d3+RoMFYjOYoYhFW8=,tag:/Sg5NpdfguAUqqrt5snoKA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3eFpJNENGSVA1Y0tuTDd3
            eGJCbnRPYzlsdXovTzJrbW85TTNBRm81KzJNCjVWemtoaFFxMjNuN1ZMK0Q2QURL
            SmtCRjVKcDh3Y1dsTjN4bHhIZzgrOHcKLS0tIFhlR2szMVY3cmdqYm5ZN1dNWXBG
            SUNzdHVXVURNUzJhWnArNERoYUtLZTgKy7V5m2N0IJklLeAr+VOAINOlP8XWSfOk
            S82wmpsZ/7EFB2opK5GjrAhSB25OxnJLUpCIhJi1nr5ebqzgE/dtGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wxuxlngq2cf4jsxfw5v2cwd0p8jxwqkjxvy0vhsmg9wuktey0vcs7q79zx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T22:13:32Z"
    mac: ENC[AES256_GCM,data:uBZVCAnA4xjdIrYXZ8Z4zddkoH859k+/MT53Nrp7H1Zi5ww91CIHuXQfpXW2uedmBVZTOOO0Rmvjeu3+0FY7b7bg6G2MS90xPA/awYjJiUGtER3bramckSoxoXlZIIWduhjS8w2RdovSagDnAJS60pq5S5Rmlw0FlcmI7CWx1qE=,iv:/FT0TpeRISESGakqayTFlmolSbLrWsUkhfkBmDfChuk=,tag:UKY+Toio3gKcCuufstdP1A==,type:str]
    version: 3.13.1
