---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: {{ .Values.namespace }}
spec:
  serviceName: database-headless
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: postgres
          image: docker.io/postgres:{{ .Values.database.image.tag }}{{ with .Values.database.image.digest }}@{{ . }}{{ end }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.database.databaseName | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.database.databaseUsername | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: dbPassword
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: storage
              mountPath: /var/lib/postgresql/data
              subPath: db-data
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mealie-storage
