---
namespace: &ns traefik # Only used in the custom namespace template manifest
traefik:
  namespaceOverride: *ns
  additionalArguments:
    - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
    - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
  image:
    tag: "v3.7.5"

