---
- name: Ensure tailscale apt repository is present
  ansible.builtin.deb822_repository:
    name: tailscale
    types: deb
    uris: https://pkgs.tailscale.com/stable/debian
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: main
    signed_by: "https://pkgs.tailscale.com/stable/debian/{{ ansible_facts['distribution_release'] }}.asc"
    state: present

- name: Ensure tailscale is installed
  ansible.builtin.apt:
    name: tailscale
    state: present
    update_cache: true # Updates the cache, such that the packages of the newly added repo are available for installation.

- name: Ensure tailscaled service is enabled and started
  ansible.builtin.service:
    name: tailscaled
    enabled: true
    state: started

