---
- name: Ensure intel microcode update is installed
  ansible.builtin.package:
    name: "{{ processor_microcode_package }}"
    state: present

- name: Ensure timezone data (tzdata) is installed
  ansible.builtin.package:
    name: tzdata
    state: present

- name: Ensure timezone is configured correctly
  ansible.builtin.file:
    src: /usr/share/zoneinfo/Europe/Zurich
    dest: /etc/localtime
    state: link

# Used to allow the creation of usermapping from container to host when using rootless containers
- name: Ensure shadow-uidmap is installed
  ansible.builtin.package:
    name: shadow-uidmap
    state: present

- name: Ensure podman is installed
  ansible.builtin.package:
    name: podman
    state: present

- name: Ensure acl is installed to allow for ansible to perform user switching to unprivileged user
  ansible.builtin.package:
    name: acl
    state: present

- name: Ensure tun module is loaded, as podman needs the network tunnel interface device (/dev/net/tun)
  community.general.modprobe:
    name: tun
    state: present

- name: Ensure ip_tables and iptable_nat modules are loaded, as podman and awall need them for networking
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - ip_tables
    - iptable_nat

- name: Mount cgroup2 at /sys/fs/cgroup, as crun needs this to run containers
  ansible.builtin.mount:
    path: /sys/fs/cgroup
    src: none
    fstype: cgroup2
    state: mounted

- name: Ensure s6 is installed
  ansible.builtin.package:
    name: s6
    state: present

- name: Ensure services defined in /etc/local.d are started on system startup (the ansible playbook will define custom reboot scripts here, e.g. s6 startup scripts)
  ansible.builtin.service:
    name: local
    state: started
    enabled: true

