---
- name: Configure daisy node
  hosts: daisy
  roles:
    - mirror
    - base
    - firewall
    - firewall/dns
    - traefik
    - service/pihole
    - service/homeassistant
    - service/karakeep
    # - dhcp # TODO once isp fixes the closed dns port issue

