---
- name: Configure daisy node
  hosts: daisy
  roles:
    - python
    - sshd
    - mirror
    - base
    - tailscale
    - mount/daisy
    - firewall
    - traefik
    - service/pihole
    - service/homeassistant
    - service/karakeep
    - service/miniflux
    - service/mealie
    # - dhcp # TODO once isp fixes the closed dns port issue

