---
- name: Configure server node
  hosts: deployserver
  roles:
    - mirror
    - base
    - firewall
    - traefik
    - service/immich
    - service/filebrowser
    - service/photoprism
    - service/gitea

