Vagrant.configure("2") do |config|
  config.vm.define "dev" do |charon|
    charon.vm.synced_folder ".", "/vagrant", disabled: true
    charon.vm.box = "debian/trixie64"
    charon.vm.box_version = "13.20260121.1"
    charon.vm.hostname = "charon"
    charon.vm.network :forwarded_port, guest: 22, host: 10022, id: "ssh"
    charon.vm.network :forwarded_port, guest: 80, host: 80, id: "port-forwarded-to-traefik-http"
    charon.vm.network :forwarded_port, guest: 443, host: 443, id: "port-forwarded-to-traefik-https"
    charon.vm.network :forwarded_port, guest: 10080, host: 10080, id: "traefik-http"
    charon.vm.network :forwarded_port, guest: 10443, host: 10443, id: "traefik-https"
    charon.vm.network :forwarded_port, guest: 20000, host: 20000, id: "immich"
    charon.vm.network :forwarded_port, guest: 20100, host: 20100, id: "filebrowser"
    charon.vm.network :forwarded_port, guest: 20200, host: 20200, id: "photoprism"
    charon.vm.network :forwarded_port, guest: 20300, host: 20300, id: "gitea"
    charon.vm.network :forwarded_port, guest: 20322, host: 20322, id: "gitea-ssh"
    charon.vm.network :forwarded_port, guest: 21000, host: 21000, id: "syncthing"
    charon.vm.network :forwarded_port, guest: 21001, host: 21001, id: "syncthing-sync"

    charon.vm.provider "libvirt" do |lv|
      lv.memory = 8192
      lv.cpus = 4
      lv.storage :file, :size => '500M', :device => 'vdb'
      lv.storage :file, :size => '500M', :device => 'vdc'
    end

    charon.vm.provision "path-setup", type: "shell", path: '../scripts/debian/path-setup'
    charon.vm.provision "source-setup", type: "shell", path: '../scripts/debian/source-setup'
    charon.vm.provision "update-setup", type: "shell", path: '../scripts/debian/update-setup'
    charon.vm.provision :reload # reboot needed to load potentially new kernel.
    charon.vm.provision "ansible", type: "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "../../../ansible/charon.yaml"
      ansible.become = true # start ansible script with sudo and let the playbook handle privilege changes from there.
      ansible.groups = {
        "charon" => [ "dev" ],
      }
      ansible.ask_vault_pass = true
      ansible.raw_arguments = [
        "--extra-vars=@../../../ansible/host_vars/dev/shared-secrets.yaml",
        "--extra-vars=@../../../ansible/host_vars/dev/charon.yaml",
        "--skip-tags=prod-only",
      ]
    end
  end
end
