---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: {{ .Values.namespace }}
spec:
  serviceName: database-headless
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: postgres
          image: ghcr.io/immich-app/postgres:{{ .Values.database.image.tag }}{{ with .Values.database.image.digest }}@{{ . }}{{ end }}
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: dbDatabaseName
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: dbUsername
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: dbPassword
            - name: POSTGRES_INITDB_ARGS
              value: "--data-checksums"
            - name: DB_STORAGE_TYPE
              value: HDD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: immich-storage

