---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
spec:
  serviceName: redis-headless
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: docker.io/valkey/valkey:{{ .Values.redis.image.tag }}{{ with .Values.redis.image.digest }}@{{ . }}{{ end }}
          command: ["redis-server", "/etc/redis/redis.conf"]
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: storage
              mountPath: /data
              subPath: redis
            - name: config
              mountPath: /etc/redis
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: immich-storage
        - name: config
          configMap:
            name: redis-config-map

