---
# See configuration here: https://k3d.io/v5.8.3/usage/configfile/
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: homelab-local-cluster
servers: 1
agents: 1
image: rancher/k3s:v1.36.1-k3s1 # This pins the k3s image and kubernetes version used in local development

