---
- name: Ensure timezone data (tzdata) is installed
  ansible.builtin.package:
    name: tzdata
    state: present

- name: Ensure timezone is configured correctly
  ansible.builtin.file:
    src: /usr/share/zoneinfo/Europe/Zurich
    dest: /etc/localtime
    state: link

# Used for exposing ports to the host when using rootless containers
- name: Ensure slirp4netns is installed
  ansible.builtin.package:
    name: slirp4netns
    state: present

- name: Ensure podman is installed
  ansible.builtin.package:
    name: podman
    state: present

