---
- name: Ensure timezone data (tzdata) is installed
  ansible.builtin.package:
    name: tzdata
    state: present

- name: Ensure timezone is configured correctly
  ansible.builtin.file:
    src: /usr/share/zoneinfo/Europe/Zurich
    dest: /etc/localtime
    state: link

# Used for exposing ports to the host when using rootless containers
- name: Ensure slirp4netns is installed
  ansible.builtin.package:
    name: slirp4netns
    state: present

# Used to allow the creation of usermapping from container to host when using rootless containers
- name: Ensure shadow-uidmap is installed
  ansible.builtin.package:
    name: shadow-uidmap
    state: present

# This is needed for the podman user to be able to create pseudo root and other users inside the container that are then
# mounted to a none root user with a uid and gid inside of the specified range on the host system.
- name: Ensure subuid and subgid ranges are defined for podman user to use
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    regexp: "^{{ podman_user }}"
    line: "{{ podman_user }}:100000:65536"
    state: present
    create: true
    insertafter: EOF
  loop:
    - "/etc/subuid"
    - "/etc/subgid"

- name: Ensure podman is installed
  ansible.builtin.package:
    name: podman
    state: present

- name: Ensure acl is installed to allow for ansible to perform user switching to unprivileged user
  ansible.builtin.package:
    name: acl
    state: present

- name: Ensure tun module is loaded, as podman needs the network tunnel interface device (/dev/net/tun)
  community.general.modprobe:
    name: tun
    state: present

- name: Mount cgroup2 at /sys/fs/cgroup, as crun needs this to run containers
  ansible.builtin.mount:
    path: /sys/fs/cgroup
    src: none
    fstype: cgroup2
    state: mounted

