---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: chrome-netpol-egress
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      connectsToBrowser: "true"
  policyTypes:
    - Egress
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: chrome
      ports:
        - protocol: TCP
          port: {{ .Values.chrome.port }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: chrome-netpol-ingress
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: chrome
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              connectsToBrowser: "true"
      ports:
        - protocol: TCP
          port: {{ .Values.chrome.port }}
