---
apiVersion: v1
kind: Service
metadata:
  name: chrome
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: chrome
  ports:
    - port: {{ .Values.chrome.port }}
      targetPort: {{ .Values.chrome.port }}
