---
apiVersion: v1
kind: Service
metadata:
  name: meilisearch
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: meilisearch
  ports:
    - port: {{ .Values.meilisearch.port }}
      targetPort: {{ .Values.meilisearch.port }}
