{{-
  $args := dict
    "Values" .Values
    "Release" .Release
    "appName" "server"
    "host" .Values.server.host
    "port" .Values.server.port
-}}
{{ include "common.netpol.defaultIngress" $args }}
