---
namespace: &ns cert-manager # Only used by the custom templates
cert-manager:
  namespace: *ns
  crds:
    enabled: true # This actually installs the crds into the cluster, disabled by default
  extraArgs:
    - --dns01-recursive-nameservers-only
    - --dns01-recursive-nameservers=1.1.1.1:53,8.8.8.8:53
