---
keys:
  - &prod_key age1wxuxlngq2cf4jsxfw5v2cwd0p8jxwqkjxvy0vhsmg9wuktey0vcs7q79zx

creation_rules:
  - path_regex: apps/overlays/prod/secrets/.*\.enc\.yaml$
    encrypted_regex: ^(data|stringData)$
    age: *prod_key

