apiVersion: v1
kind: Secret
metadata:
    name: secret
    namespace: immich
type: Opaque
stringData:
    dbPassword: ENC[AES256_GCM,data:nHDOLSU/oDQW3d95HYA+1xboK93u+bDCxfuf5/jY7kA=,iv:omvxFNgdcvrpsGIEYKuhD0TcKCU3Jdu8bBNOYb99IVA=,tag:3BN52lgmLfDFIdlkhKuG4g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiT1hLYmVWcEk2YlFKL2oz
            MU9MUnZFSW44c2FGVTdjcjNlaHVrOTAzZUNBCjBBWVJ1UTZuVEx0YzdiZVlhME5U
            ajRPc2xuc0x4aG1zR2grNE9GZGlkdmMKLS0tIGhnWkY1VnhWRGtGeE1zZXNmRndu
            eUpFcHFGbUpJTFpRaE9kdXM1NFJlU3MK+uMdSw1+jnmD4Q/4LjZDCH2q3T4JdI7h
            DPNQMomr8ReNEExEDCim3MY79iHKu9xzku/PHK+jYUhs8iPZ4Ul6eA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wxuxlngq2cf4jsxfw5v2cwd0p8jxwqkjxvy0vhsmg9wuktey0vcs7q79zx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T08:53:09Z"
    mac: ENC[AES256_GCM,data:77EGVvYzttlKy3Ezrl5FTzIG5DPb8xYoMu8mvxwkqIDk9lQ1HlxJbuSX/BOQp4VGQ7d0dwdvyK2TS7MQiA7bFuRyeS/oZ5ekjvvH6BbkWOrVfXwUfluo6zTmN0L08E9SRM2FozZt6YFFmgMoYtO7eII7fACN0UO4Fsm3LERj4sI=,iv:rMOfMWLGPrYZEMsoFBRDg9ZGcCtbkXRSn1uvffg+PgU=,tag:PxGo8S4pkVrtjSl07rn1eQ==,type:str]
    version: 3.13.1
