apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: secret
    namespace: kimai
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: dbPassword
          stringData: ENC[AES256_GCM,data:c9dYnkuoYN/r0wTPKuYZenBZbkuhyt2D8YqrK40cEqs=,iv:cp/VvxC3cWTOMpnrI5BZ4XAMseXkf4w0IU6r6gRpVrY=,tag:3jgdCOoW70pRAh/asXhj4g==,type:str]
        - name: dbRootPassword
          stringData: ENC[AES256_GCM,data:hmOU+EQn2irFjEjUEapcGacnaNmJmZM+pJjU2ijiVB8=,iv:XaIbcFIgaPY5sjEr9UKSrk6fVDk3hX7MVIIcXQfHXLA=,tag:2vIN0cZ94ql1/VvNxERwnw==,type:str]
        - name: appSecret
          stringData: ENC[AES256_GCM,data:oU5Acm+pr8Ldf8wELnL8jsgj4oCf6jk11VE5WMuR7II=,iv:jVihtKw+RugnojxaorMqkIn+QOdyN/8KuMJfBEZwJpw=,tag:V3wKLkfyA9RTC/r/o1lXwg==,type:str]
        - name: adminEmail
          stringData: ENC[AES256_GCM,data:Y0aPiDtDVfDprvlGReOaQCpVdIUUZgnK,iv:D38jcDtURJq+k3QECmH/Qm1131quZMgqmzJYvYz/M+o=,tag:IQI8KZG4cO+ft2qLdtqHLg==,type:str]
        - name: adminPassword
          stringData: ENC[AES256_GCM,data:Msf3wFClCcKgEy0nKhvxshEFvHJVaJf0gqv5xZYnWmo=,iv:2+CCUxVXgO5AF6mP3NkrEf2lwBZSaKbncgzLSD0xBPc=,tag:0FuL2I/zXQp3rG40b3IwSw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQTByOVJUeEpqUGREZzh5
            RTcvR3QwNFd4bllUeHRiWlNVWGgzN2ZncjFVCjZONWhsbnNJdlkxM3lDWkJ5aVA3
            cmFWZTN0UlpxWXl4OVN0bE1UcGlKOEUKLS0tIC9jaGw0Z3gxampydjBmbVorL3p2
            WDlaYk56ZDEzOEpwOTY1WTZPbDNvYUEKywgy3ewpDdjcLGUBrB7nf856mVaTw8WI
            WK+GsWH8vgbdc+wvbY5MPYi8ozcRB+xtz1rzzzlSY01mD8fTW4xA3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wxuxlngq2cf4jsxfw5v2cwd0p8jxwqkjxvy0vhsmg9wuktey0vcs7q79zx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-10T22:50:36Z"
    mac: ENC[AES256_GCM,data:gPXF5i0BWcObzfVvfp6wIGaMM5TynnYJwt9Vg4WyMplLjUt8ME/ViK8mBt0lSEiDs6ogAuWJkVvRBIriascesWCssU0sOp1kfeKtkCv3zwiybr/Ihs4H0Ks76KXQxvmSP9tTZgd8dCPde279dTbJFXdEt5piXzsEZ49VHV06Pmw=,iv:LQybrPR6/uksK1bOLNXh9EiSqUms++vdvsLUXki66QM=,tag:RPAtJFxx0Z0gFiw2ml4aVw==,type:str]
    version: 3.13.1
