---
apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: kimai
type: Opaque
stringData:
  dbPassword: kimai-db-password
  dbRootPassword: kimai-root-password
  appSecret: change_this_to_something_unique
  adminEmail: admin@example.com
  adminPassword: admin123

