apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: secret
    namespace: kimai
spec:
    # suspend reconciliation of the sops secret object
    suspend: false
    secretTemplates:
        - name: secret
          stringData:
            dbPassword: ENC[AES256_GCM,data:vUeIidXUESlPnWxV3rJ/7lPgTbsT0EFGF2xTaLB0KN8=,iv:Cen7NA6uoGcOqWspGqmx8miGj0cGyePqQKE5tZcyKQg=,tag:sqGpd43UDgtCU78c/DRUVQ==,type:str]
            dbRootPassword: ENC[AES256_GCM,data:3jL45NOEyK6jZELX1YlcjJjw7aLBdWNZDfo8hU7wZmg=,iv:zk9QNQOH3kl+dQ9JJddJNi1YtV6dJavRnoPucNy6J6c=,tag:OHbk0Wr4VJrWwJST9jMfeA==,type:str]
            appSecret: ENC[AES256_GCM,data:Uwz4tgqyDq4cy6ZZHqibJPflnz5iuJRaFcShCEqLZHg=,iv:+mqerS2XeqM0QXR0blHg71ChwlH1w686KcXYBjmFalI=,tag:n53RnRP7RqoXJuLPgVanyA==,type:str]
            adminEmail: ENC[AES256_GCM,data:qx+DgMv794StvcRXVIn4pO9wwMtt6e/i,iv:RLLlGGUeK4savV+Px6XtS84/XAJX9tm1XrKSlRjH5Pw=,tag:k4hFOZ3MAPEFKfgSVUzyaA==,type:str]
            adminPassword: ENC[AES256_GCM,data:zQ515mUzEXd379pOvrAPX9V6Hsx2P21iskWBC/K6nGs=,iv:uTs2G9/EyJzn9Jnrz+LEQv+JLGOTPHom1w3oO9Gf4GI=,tag:4+tOtPvsktAy03OLST2WKA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQTByOVJUeEpqUGREZzh5
            RTcvR3QwNFd4bllUeHRiWlNVWGgzN2ZncjFVCjZONWhsbnNJdlkxM3lDWkJ5aVA3
            cmFWZTN0UlpxWXl4OVN0bE1UcGlKOEUKLS0tIC9jaGw0Z3gxampydjBmbVorL3p2
            WDlaYk56ZDEzOEpwOTY1WTZPbDNvYUEKywgy3ewpDdjcLGUBrB7nf856mVaTw8WI
            WK+GsWH8vgbdc+wvbY5MPYi8ozcRB+xtz1rzzzlSY01mD8fTW4xA3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wxuxlngq2cf4jsxfw5v2cwd0p8jxwqkjxvy0vhsmg9wuktey0vcs7q79zx
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-14T19:07:20Z"
    mac: ENC[AES256_GCM,data:pi8TyD8pmj51kfKD4hds4npj7jXl1PA3/6JQCXVGlHqokAkXGiDWWplXkS+QB91WqZuSgSh2Rr2Qb/phszyLCetXThrpnjTo70EJjqzHssJ8y8ObFBqMwj9aN034MKrKw26JAvhd4GRJ9UzYViegoBiz0E5oMibKCK1AbiXPaKI=,iv:EYMLmgYwwfP33Wxc16cF8EjhcRsd8oEh0nTkgEmr8VA=,tag:i2siYGtZVozGscYQrVEIlA==,type:str]
    version: 3.13.1
