{{-
  $args := dict
    "Values" .Values
    "Release" .Release
    "appName" "deluge"
    "host" .Values.deluge.host
    "port" .Values.deluge.port
-}}
{{ include "common.netpol.defaultIngress" $args }}
