{{-
  $args := dict
    "Values" .Values
    "Release" .Release
    "appName" "jellyfin"
    "host" .Values.jellyfin.host
    "port" .Values.jellyfin.port
-}}
{{ include "common.netpol.defaultIngress" $args }}
