---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: jellyfin
  ports:
    - port: {{ .Values.jellyfin.port }}
      targetPort: 8096
