---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: prowlarr
  ports:
    - port: {{ .Values.prowlarr.port }}
      targetPort: 9696
