Vagrant.configure("2") do |config|
  config.vm.define "dev" do |daisy|
    daisy.vm.box = "generic/debian12"
    daisy.vm.box_version = "4.3.12"
    daisy.vm.hostname = "daisy"
    daisy.vm.network :forwarded_port, guest: 22, host: 10122, id: "ssh"
    daisy.vm.network :forwarded_port, guest: 80, host: 80, id: "port-forwarded-to-traefik-http"
    daisy.vm.network :forwarded_port, guest: 443, host: 443, id: "port-forwarded-to-traefik-https"
    daisy.vm.network :forwarded_port, guest: 10080, host: 10080, id: "traefik-http"
    daisy.vm.network :forwarded_port, guest: 10443, host: 10443, id: "traefik-https"
    daisy.vm.network :forwarded_port, guest: 20400, host: 20400, id: "pihole"
    daisy.vm.network :forwarded_port, guest: 20453, host: 20453, id: "pihole-dns"
    daisy.vm.network :forwarded_port, guest: 20500, host: 20500, id: "homeassistant"
    daisy.vm.network :forwarded_port, guest: 20600, host: 20600, id: "karakeep"
    daisy.vm.network :forwarded_port, guest: 20700, host: 20700, id: "miniflux"

    daisy.vm.provider "libvirt" do |lv|
      lv.memory = 8192
      lv.cpus = 4
      lv.storage :file, :size => '500M', :device => 'vdb'
    end

    daisy.vm.provision "vm-setup", type: "shell", inline: <<-SHELL
      echo "Add sbin to path variable, as it contains necessary applications and is available in the standard pi-os"
      echo 'export PATH="$PATH:/sbin:/usr/sbin"' >> /etc/profile.d/sbin-path.sh
      chmod +x /etc/profile.d/sbin-path.sh

      if [ ! -b /dev/vdb1 ]; then
        echo "Partitioning /dev/vdb..."
        echo 'type=83' | sudo sfdisk /dev/vdb
        echo "Formatting /dev/vdb1 as ext4..."
        sudo mkfs.ext4 /dev/vdb1
      else
        echo "/dev/vdb1 already exists, skipping disk setup."
      fi

      echo "Upgrade all installed packages including the kernel..."
      sudo truncate -s 0 /etc/apt/sources.list
      sudo echo "deb https://debian.ethz.ch/debian stable main contrib non-free" >> /etc/apt/sources.list
      sudo echo "deb-src https://debian.ethz.ch/debian stable main contrib non-free" >> /etc/apt/sources.list
      sudo apt update
      # TODO: This takes way to long, find better box that does not require so many updates.
      # sudo DEBIAN_FRONTEND=noninteractive apt -y \
      #   -o Dpkg::Options::="--force-confdef" \
      #   -o Dpkg::Options::="--force-confold" upgrade
      echo "Install required packages..."
      sudo DEBIAN_FRONTEND=noninteractive apt -y \
        -o Dpkg::Options::="--force-confdef" \
        -o Dpkg::Options::="--force-confold" install \
        python3

      echo "Reboot needed to load potentially new kernel. Run 'vagrant reload' to reboot the VM..."
    SHELL

    daisy.vm.provision "ansible", type: "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "../../../ansible/daisy.yaml"
      ansible.become = true # start ansible script with sudo and let the playbook handle privilege changes from there.
      ansible.groups = {
        "daisy" => [ "dev" ],
      }
      ansible.ask_vault_pass = true
      ansible.raw_arguments = [
        "--extra-vars=@../../../ansible/vars/dev/shared-secrets.yaml",
        "--extra-vars=@../../../ansible/vars/dev/daisy.yaml",
        "--skip-tags=prod-only",
      ]
    end
  end
end
