Vagrant.configure("2") do |config|
  config.vm.define "dev" do |daisy|
    daisy.vm.synced_folder ".", "/vagrant", disabled: true
    daisy.vm.box = "debian/trixie64"
    daisy.vm.box_version = "13.20260121.1"
    daisy.vm.hostname = "daisy"
    daisy.vm.network :forwarded_port, guest: 22, host: 10122, id: "ssh"
    daisy.vm.network :forwarded_port, guest: 80, host: 80, id: "port-forwarded-to-traefik-http"
    daisy.vm.network :forwarded_port, guest: 443, host: 443, id: "port-forwarded-to-traefik-https"
    daisy.vm.network :forwarded_port, guest: 10080, host: 10080, id: "traefik-http"
    daisy.vm.network :forwarded_port, guest: 10443, host: 10443, id: "traefik-https"
    daisy.vm.network :forwarded_port, guest: 20400, host: 20400, id: "pihole"
    daisy.vm.network :forwarded_port, guest: 20453, host: 20453, id: "pihole-dns"
    daisy.vm.network :forwarded_port, guest: 20500, host: 20500, id: "homeassistant"
    daisy.vm.network :forwarded_port, guest: 20600, host: 20600, id: "karakeep"
    daisy.vm.network :forwarded_port, guest: 20700, host: 20700, id: "miniflux"

    daisy.vm.provider "libvirt" do |lv|
      lv.memory = 8192
      lv.cpus = 4
      lv.storage :file, :size => '500M', :device => 'vdb'
    end

    daisy.vm.provision "path-setup", type: "shell", path: '../scripts/debian/path-setup'
    daisy.vm.provision "disk-setup", type: "shell", path: 'scripts/disk-setup'
    daisy.vm.provision "source-setup", type: "shell", path: '../scripts/debian/source-setup'
    daisy.vm.provision "update-setup", type: "shell", path: '../scripts/debian/update-setup'
    daisy.vm.provision :reload # reboot needed to load potentially new kernel.
    daisy.vm.provision "ansible", type: "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "../../../ansible/daisy.yaml"
      ansible.become = true # start ansible script with sudo and let the playbook handle privilege changes from there.
      ansible.groups = {
        "daisy" => [ "dev" ],
      }
      ansible.ask_vault_pass = true
      ansible.raw_arguments = [
        "--extra-vars=@../../../ansible/vars/dev/shared-secrets.yaml",
        "--extra-vars=@../../../ansible/vars/dev/daisy.yaml",
        "--skip-tags=prod-only",
      ]
    end
  end
end
